-- UPDATE

IF EXISTS (SELECT * FROM INSERTED) AND EXISTS (SELECT * FROM DELETED)

-- INSERT

IF EXISTS (SELECT * FROM INSERTED) AND NOT EXISTS (SELECT * FROM DELETED)

-- DELET

IF NOT EXISTS (SELECT * FROM INSERTED) AND EXISTS (SELECT * FROM DELETED)