CREATE TABLE PATRICIA
(
	ID_P INT PRIMARY KEY,
	NOME VARCHAR (50),
	CPF NUMERIC (11) UNIQUE
)

DROP TABLE PATRICIA

INSERT INTO PATRICIA VALUES ('1','PATRICIA',123456789)
INSERT INTO PATRICIA VALUES ('2','PADOVA',40411890808)

SELECT * FROM PATRICIA

CREATE OR ALTER PROCEDURE ALTERA
(
	@NOME VARCHAR (50),
	@CPF NUMERIC (19),
	@ID_P INT
)
AS
BEGIN

DECLARE
@NOME2 VARCHAR(50)

SELECT @NOME2 = NOME FROM PATRICIA WHERE CPF= @CPF AND @ID_P != ID_P

IF(@NOME2 IS NOT NULL)
PRINT CONVERT(VARCHAR(11), @CPF) + ' JÁ PERTENCE A ' + @NOME2

UPDATE PATRICIA
SET 
NOME = @NOME,
CPF = @CPF
WHERE ID_P = @ID_P

END;



EXEC ALTERA 'PAREICIA', 40411890808, 1