if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[USP_INSERIR_PESSOA_FISICA]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[USP_INSERIR_PESSOA_FISICA]
GO

/* PARA CRIAR UMA TABELA PK E FK (VOCÊ SÓ VAI PODER INSERIR NA TABELA PESSOA FISICA DEPOIS Q A TABELA PESSOAS ESTIVER PREENCHIDA, 
E SÓ PODERÁ EXCLUIR DA PESSOA FISICA SE A PESSOAS ESTIVER EXCLUÍDA PRIMEIRO.

CREATE TABLE PESSOAS
(
	ID_PESSOA_FISICA INT IDENTITY(1,1) PRIMARY KEY,
	ID_PESSOA_TIPO	 INT
);

CREATE TABLE PESSOA_FISICA
(
	ID_PESSOA_FISICA		INT IDENTITY(1,1) PRIMARY KEY,
	NOME					VARCHAR (225),
	CPF						VARCHAR (11),
	RG						VARCHAR (20),
	DATA_NASCIMENTO			DATE
	CONSTRAINT FK_PESSOAS	FOREIGN KEY (ID_PESSOA_FISICA) REFERENCES PESSOAS(ID_PESSOA_FISICA),
)


 */

CREATE PROCEDURE USP_INSERIR_PESSOA_FISICA
(
@NOME			  VARCHAR (50)=NULL, 
@CPF			  VARCHAR (11) = NULL,
@RG				  VARCHAR (20) = NULL,
@DATA_NASCIMENTO  DATE = NULL

)
AS
BEGIN
	BEGIN TRY
		BEGIN TRAN

		IF EXISTS (SELECT CPF FROM PESSOA_FISICA WHERE CPF = @CPF)
			BEGIN
				RAISERROR ('ESTE CPF JÁ ESTÁ CADASTRADO NO SISTEMA',14,1);
			END;

			DECLARE
				@ID_PESSOA INT;

	-- 1 INSERIR NA TABELA PESSOAS
	
			SET IDENTITY_INSERT PESSOAS OFF; -- ATIVAR ESTE COMANDO PARA PODER LIGAR O @@IDENTITY.

			INSERT INTO PESSOAS (ID_PESSOA_TIPO)
			VALUES(1);

			SET @ID_PESSOA = @@IDENTITY; -- RETORNA O ULTIMO ID QUE FOI INSERIDO

	-- 2 INSERIR NA TABELA PESSOA_FISICA
	--SEMPRE QUE TIVERMOS UMA PK É NECESSARIO PEGAR A PRIMEIRA PK E ALIMENTAR EM UMA VARIAVEL, E DEPOIS INSERIR ESSA VARIAVEL NA OUTRA TABELA.

			INSERT INTO PESSOA_FISICA (ID_PESSOA_FISICA,NOME,CPF,RG,DATA_NASCIMENTO)
			VALUES (@ID_PESSOA,@NOME,@CPF,@RG,@DATA_NASCIMENTO);

			SELECT @ID_PESSOA AS RETORNO;

		COMMIT TRAN
	END TRY
	BEGIN CATCH	
		ROLLBACK TRAN
			SELECT ERROR_MESSAGE () AS RETORNO;
	END CATCH
END;

-- OBS: NUNCA DEIXAR SEU EXEC ATIVO NA PROC QUE DA BO DEPOIS.

--EXEC USP_INSERIR_PESSOA_FISICA 'bruno padoveze','42612253879','925988555','19940507'

SELECT * FROM PESSOAS

SELECT * FROM PESSOA_FISICA