if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[USP_COSULTAR_CLINETES_ATIVOS]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[USP_COSULTAR_CLINETES_ATIVOS]
GO

CREATE PROCEDURE USP_COSULTAR_CLINETES_ATIVOS
(
	@ID_CLIENTE		INT = NULL,
	@NOME			VARCHAR (150) = NULL,
	@ATIVO			BIT = NULL,
	@DATA_CADASTRO	DATE = NULL
)
AS
BEGIN

IF @ATIVO = 1
	BEGIN
		SELECT 	ID_CLIENTE,
				NOME,
				ATIVO,
				DATA_CADASTRO
		FROM TBLCLIENTES
		WHERE ID_CLIENTE = @ID_CLIENTE -- COLOCAR O WHERE PARA PESQUISAR APENAS UM ITEM, E DEIXAR SEM PARA PESQUISAR UMA LISTA COMPLETA
	END
	ELSE
		BEGIN
			RAISERROR ('CLIENTE INDISPONIVEL', 14,1); --PADRÃO PARA GERAÇÃO DE ERRO
		END
END;

-- EXECUTAR PARA ATUALZIAR A PROC NO BANCO -- CONTROL + SHIFT + R
-- OBS: NUNCA DEIXAR O EXEC DE TESTE DENTRO DA PROC

EXEC USP_COSULTAR_CLINETES_ATIVOS null,NULL,1,NULL