if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[USP_COSULTAR_CLINETES]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[USP_COSULTAR_CLINETES]
GO

CREATE PROCEDURE USP_COSULTAR_CLINETES
(
	@ID_CLIENTE		INT = NULL,
	@NOME			VARCHAR (150) = NULL,
	@ATIVO			BIT = NULL,
	@DATA_CADASTRO	DATE = NULL
)
AS
BEGIN
	SELECT 	ID_CLIENTE,
			NOME,
			ATIVO,
			DATA_CADASTRO
	FROM TBLCLIENTES
	WHERE ID_CLIENTE = @ID_CLIENTE -- COLOCAR O WHERE PARA PESQUISAR APENAS UM ITEM, E DEIXAR SEM PARA PESQUISAR UMA LISTA COMPLETA
END;

-- EXECUTAR PARA ATUALZIAR A PROC NO BANCO -- CONTROL + SHIFT + R
-- OBS: NUNCA DEIXAR O EXEC DE TESTE DENTRO DA PROC

EXEC USP_COSULTAR_CLINETES 2